---
title: "R Notebook"
output: pdf_notebook
---

```{r}
## app.R ##
library(DT)
library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)
library(rvest)
```

# Scraping data
-The chunck bellow is used for scraping the data
```{r}
print("Please Wait, Web Scraping In-progress...")

url= "https://www.jumia.co.ke/"

# reading url
page = read_html(url)

# Extracting all category tabs that contain all the products 
divs = page %>% html_nodes("div[class='col16 -pvs']") #saving to div variable

# creating an empty data frame to save the data
jumia = tibble(  "Name"= character(),      # name column
         "Price" =character(),             # price column
         "Discount" =character(),          # discount column
         "Category"= character())          # category column
# Extracting all category tabs that contain all the products 
divs = page %>% html_nodes("div[class='col16 -pvs']") #saving to div variable

# creating an empty data frame to save the data
jumia = tibble(  "Name"= character(),      # name column
         "Price" =character(),             # price column
         "Discount" =character(),          # discount column
         "Category"= character())          # category column


# creating a function that extracts all the products information in a certain category
category = function(div){ # passing a div parameter
  
  # assigning category as the div's title/header in the website
  category = div  %>%html_nodes("h2") %>% html_text()  # text in the h2 tag
  
  # if a category contains see all link
  see_all_link = div %>% html_nodes("a[class='-df -i-ctr -upp -m -mls -pvxs']")%>% html_attr("href")
  
  if (length(see_all_link)){
    
    url_ = paste0(url,see_all_link %>%  stringr::str_extract( "([^/]+)/$") )
    new_page = read_html(url_)
    products = new_page %>%   
      html_nodes("div[data-catalog='true']") %>%
      html_nodes("article")
    
    # scraping the various product attributes
    name = products %>% html_node("h3[class='name']")%>%
      html_text()
    price = products %>% html_node("div[class='prc']") %>%
      html_text()
    discount = products %>% 
      html_node("div[class='bdg _dsct _sm']") %>% html_text() 
   
    
    # scarping the bottom pages in our new page of all categories
    next_page_link = new_page %>% html_node("a[aria-label='Next Page']") %>% html_attr("href")
    
    while(!is.na(next_page_link)) {
      url_page = paste0(url_, next_page_link %>%  stringr::str_extract( "\\?([^/]+)$") ) # getting url for that page
      new_page = read_html(url_page)                                                     #reading the page contents

      products = new_page %>% html_nodes("div[data-catalog='true']") %>%  html_nodes("article")
      
        # scraping all product from this page
      name_ = products %>% html_node("h3[class='name']")%>%
        html_text()
      price_ = products %>% html_node("div[class='prc']") %>%
        html_text()
      discount_ = products %>% 
        html_node("div[class='bdg _dsct _sm']") %>% html_text() 

      name=c(name,name_); price=c(price,price_); discount=c(discount,discount_)
      
      next_page_link = new_page %>% html_node("a[aria-label='Next Page']") %>% html_attr("href")
    }
    
  }
  
  else {
    # selecting all items in that div
    items = div  %>% html_nodes("div[class='itm col']") 
    name = items %>% html_node("div[class='name']") %>%
      html_text() # all item names
    price = items %>% html_node("div[class='prc']") %>%
      html_text() # all item prices
    discount = items %>% html_node("div[class='bdg _dsct']") %>%
      html_text() #all item discounts
  }
  
 # returning a data frame of the extracted items
 return(tibble( "Name"= name,  
         "Price" = price,
         "Discount" = discount,
         "Category"=  category))

}

# running the above category function to all the category divs and appending the data to the jumia data frame
for(div in divs[c(2,4:23)]){
  jumia= bind_rows(jumia,category(div))
}

# converting the price and discount columns to integers
jumia = jumia %>% 
  mutate(Price = as.numeric(jumia$Price %>% stringr::str_sub(-8) %>% 
                              stringr::str_replace_all(pattern="[^0-9]","") )
         ,
         Discount= as.numeric(Discount %>% 
                                stringr::str_replace_all(pattern="[^0-9]","")  )) 

# assigning zero to NAs in discount column
jumia$Discount[is.na(jumia$Discount)] = 0

print("Web Scraping Completed")
```


# User Inteface
-After data has peen obtained, the code below creates the apps user interface
```{r}

ui <- dashboardPage(
  
  # Dash Board title
  dashboardHeader(title = "Jumia WebScraping"),
  
  # Slider panel configuration
  dashboardSidebar(
    width = 200,
    sidebarMenu(
      menuItem("Jumia Data", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Analysis", icon = icon("line-chart"), tabName = "charts")
    )
  ),# end of sidebar
  
  # Body
  dashboardBody(
    # Boxes need to be put in a row (or column)
    tabItems(
      # website tab
      tabItem(tabName = "dashboard",  h2("Jumia Website - Data Dashboard"),
              fluidRow(
                    box(title = "Embedded Website",
                        width = 12,
                        height = "52px",
                        solidHeader = TRUE,
                        collapsible = TRUE,
                        uiOutput("tab")
                        )),
              fluidRow(
                column( width=5,
                    #price slider
                    box(title = "Table Filters",
                        sliderInput("price_slider", "Price Range", 
                                    min=0, max=max(jumia$Price),step=1000, value=c(0,40000)),
                        selectInput("category", "Select Categories", 
                                    choices = c("All",unique(jumia$Category))),
                        sliderInput("dsc_slider", "Discount Range", 
                                    min=0, max=max(jumia$Discount),step=10, value=c(0,max(jumia$Discount))),
                        width = 12, height = "350px"
                    ),
                    # Display text
                    box( 
                         verbatimTextOutput("table_info"), 
                         width = 12
                         ) 
                    ),
                column(width = 7,
                    # table box
                    box(title = "Table Output",
                        status = "primary",
                        solidHeader = TRUE,
                        collapsible = TRUE,
                        DT::dataTableOutput( "table1"),
                        #tableOutput("table1"),
                        width=12 ))
                  ) # end of fluid row
            ), #end of dashboard tab item
      #charts tab
      tabItem(tabName="charts",h2("Analysis Charts"),
              fluidRow( box(title = "Top 5 Categories with High Discounts",
                            plotOutput("charts_1"),
                            background = "olive",
                            width=12)),
              fluidRow( box(title = "Top 5 Categories with Lowest Prices",
                            plotOutput("charts_2"),
                            background = "olive",
                            width=12)),
              fluidRow( box(title = "Top 10 Products with highets Discounts",
                            plotOutput("charts_3"),
                            background = "olive",
                            width=12)
                        )
        ) #end of charts tab item   
    ) # end of tab items
  ) # end of body
) # end of ui


```

# server
-The code below created output for the UI functionalities above;
```{r}
server <- function(input, output) {
  
  
 
  output$tab <- renderUI({
    url <- a("Jumia Homepage", href="https://www.jumia.co.ke/")
    tags$a(href="https://www.jumia.co.ke/", "Click!! Open Jumia Website")
  })
  

  table <- reactiveVal(NULL)
  
  # updating the reactiveVal whenever the table output changes
  observe({
    if (input$category == "All" ) {
      table(jumia %>%
                   filter(Price >= input$price_slider[1] & Price <= input$price_slider[2]) %>% 
                   filter(Discount >= input$dsc_slider[1] & Discount <= input$dsc_slider[2]))
    } else {
      table(jumia %>% 
                   filter(Price >= input$price_slider[1] & Price <= input$price_slider[2]) %>%
                   filter(Discount >= input$dsc_slider[1] & Discount <= input$dsc_slider[2]) %>% 
                   filter(Category == input$category) )
    }
  })
  
  output$table1 <- DT::renderDataTable({
    req(table())
    datatable(
      table(),
      options =   list(
        pageLength=5,
        lengthMenu = c(5,10),
        scrollX =TRUE), 
        filter = 'none'
    )
  })
  
  #output$table1 <- renderTable({
   # req(table())
    #table()
#  })
  
  output$table_info = renderText({
      if (input$category == "All") {
        paste("Search Results:
              Number of items:", nrow(table()), "
              Category:",input$category,"
              Price Range: ",input$price_slider[1]," - ",input$price_slider[2],"
              Discount Range: ",input$dsc_slider[1]," - ",input$dsc_slider[2] )
      } else {
        paste("Search Results:
              Number of items:", nrow(table()), "
              Category:",input$category,"
              Price Range: ",input$price_slider[1]," - ",input$price_slider[2],"
              Discount Range: ",input$dsc_slider[1]," - ",input$dsc_slider[2] )
      }
    })
 
  
  # chart 1
  output$charts_1 <- renderPlot({
    plot= jumia %>% 
      group_by(Category) %>% 
      summarize(count=n(),discount= mean(Discount, na.rm = T)) %>% 
      filter(rank(desc(discount))<=5) %>% 
      ggplot(aes(x=forcats::fct_reorder(Category,desc(discount)), 
                 y=discount))+
      geom_col(fill="cadetblue4") + # bar plot layer
      geom_label(aes(label = paste(round(discount,1),"%")),
                 size=4,fontface="bold") #adding discount as text labels
    
    # formating the plot
    plot+
      # adding x and y labels
      labs(title = "Barplot of Categories Vs Discount",
           y="Discount %",
           x="Categories")+
      theme_bw()+
      # rotating the x labels
      theme(axis.text.x = element_text(angle = 90))+
      theme(axis.text = element_text(size = 10,face="bold"))
  })
  
  
  # Chart 2 
  output$charts_2 <- renderPlot({ 
    # creating plot
    plot= jumia %>% 
      group_by(Category) %>% 
      summarize(count=n(),price= mean(Price, na.rm = T)) %>% 
      filter( rank(price)<=5) %>% 
      ggplot(aes(x=forcats::fct_reorder(Category,price), 
                 y=price))+
      geom_col(fill="cadetblue4") + # bar plot layer
      geom_label(aes(label = round(price,1)),size=4,fontface="bold") #adding discount as text labels
    
    # formatting the plot
    plot+
      # adding x and y labels
      labs(title = "Barplot of Categories Vs Price",
           y="Price",
           x="Categories")+
      theme_bw()+
      # rotating the x labels
      theme(axis.text.x = element_text(angle = 90))+
      theme(axis.text = element_text(size = 10,face="bold"))
  }) 
  
  # Chart 3
  output$charts_3 <- renderPlot({
    data = jumia %>% 
      arrange(desc(Discount)) %>% 
      filter(rank(desc(Discount))<=5) %>% 
      mutate(Name=stringr::str_sub(Name,1,16))
    
    # creating the plot
    ggplot(data=data, aes(x= forcats::fct_reorder(Name,Discount),
                          y=Discount, 
                          label=paste("Price:",Price, ", -",Discount,"%")))+
      geom_col(inherit.aes = T,fill="cadetblue4")+
      geom_label(size=4,fontface="bold")+
      labs(title = "Top 10 Products with highets Discounts",
           y="Discount",
           x="Product Name")+
      theme_bw()+
      theme(axis.text.x = element_text(angle=90))+
      theme(axis.text = element_text(size = 10,face="bold"))
  })
  
  
} # end of server



```

# Runing app
```{r}
shinyApp(ui, server)
```

